import type { TheryTourAudience, TheryTourStep } from './thery-tour.types';

const PROFESSIONAL_STEPS: TheryTourStep[] = [
  {
    id: 'pro-dashboard',
    route: '/dashboard',
    target: 'nav-dashboard',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Aqui é o pulso do consultório',
    body:
      'O Dashboard mostra o dia: próxima sessão, alertas da Ivy e atalhos. Não é o prontuário — é o mapa para você decidir por onde começar.',
    ctaLabel: 'Ir para Pacientes',
    viewport: 'both',
  },
  {
    id: 'pro-new-patient',
    route: '/patients',
    target: 'cta-new-patient',
    fallbackTarget: 'nav-patients',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Cadastre o primeiro paciente',
    body:
      'Sem paciente, agenda, financeiro e copiloto ficam vazios. Toque em Novo Paciente quando quiser — o tutorial não espera o cadastro. Se aparecer a cota do plano, é o teto de pacientes ativos.',
    ctaLabel: 'Entendi',
    viewport: 'both',
  },
  {
    id: 'pro-patient-hub',
    route: '/patients/:patientId/copilot',
    target: 'patient-tabs',
    pose: 'profile',
    placement: 'spotlight',
    title: 'A central de um paciente',
    body:
      'Tudo aqui é só desta pessoa: Copiloto, Histórico de Sessões, Check-ins, Ficha Clínica, Financeiro e Documentos. Nada cruza com outro prontuário.',
    ctaLabel: 'Ver histórico',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'pro-sessions',
    route: '/patients/:patientId/overview',
    target: 'patient-tab-overview',
    fallbackTarget: 'patient-tabs',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Sessão e nota',
    body:
      'No Histórico você abre a sessão, grava ou anota. Eu ajudo a organizar o registro — quem valida e assina é você.',
    ctaLabel: 'Ver check-ins',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'pro-checkins',
    route: '/patients/:patientId/checkins',
    target: 'patient-tab-checkins',
    fallbackTarget: 'patient-tabs',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'O que chega do portal',
    body:
      'Check-ins e o diário da família ou do próprio paciente viram contexto clínico. Não é fofoca solta: é material para a próxima sessão.',
    ctaLabel: 'Ver ficha clínica',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'pro-clinical',
    route: '/patients/:patientId/clinical',
    target: 'patient-tab-clinical',
    fallbackTarget: 'patient-tabs',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Ficha clínica',
    body:
      'Anamnese, hipóteses e o quadro atual. É o registro vivo deste paciente — salve quando editar. Eu não publico sozinha.',
    ctaLabel: 'Ver financeiro',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'pro-patient-finance',
    route: '/patients/:patientId/financeiro',
    target: 'patient-tab-financeiro',
    fallbackTarget: 'patient-tabs',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Financeiro deste paciente',
    body:
      'Valor da sessão, plano e o que já foi pago desta pessoa. Diferente do Financeiro da clínica: o contrato aqui é só deste prontuário.',
    ctaLabel: 'Ver documentos',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'pro-documents',
    route: '/patients/:patientId/documents',
    target: 'patient-tab-documents',
    fallbackTarget: 'patient-tabs',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Documentos salvos',
    body:
      'Relatórios da sessão e o que você guardou do copiloto. Tudo isolado neste prontuário — nada cruza com outro paciente.',
    ctaLabel: 'Ver acesso da família',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'pro-family-invite',
    route: '/patients/:patientId/documents',
    target: 'cta-family-invite',
    fallbackTarget: 'cta-patient-actions',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Gerar acesso família',
    body:
      'Gera o código para quem acompanha este paciente entrar no app: responsável ou o próprio adulto. Sem o convite, check-ins e diário não chegam.',
    ctaLabel: 'Ver vínculo',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'pro-manage-link',
    route: '/patients/:patientId/documents',
    target: 'cta-manage-link',
    fallbackTarget: 'cta-patient-actions',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Gerenciar o vínculo',
    body:
      'Arquiva o paciente na lista inativa ou encerra o acompanhamento. O histórico clínico não some só porque saiu da agenda ativa.',
    ctaLabel: 'Ir para a Agenda',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'pro-calendar',
    route: '/calendar',
    target: 'nav-agenda',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Encaixe da semana',
    body:
      'A Agenda é o quadro de horários: marque, remarque e veja o status. Sessão realizada pode virar atendimento faturável no Financeiro.',
    ctaLabel: 'Ver Financeiro',
    viewport: 'both',
  },
  {
    id: 'pro-finance',
    route: '/financeiro',
    target: 'financeiro-tabs',
    fallbackTarget: 'nav-financeiro',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Plano, receita e classificação',
    body:
      'Visão geral, receitas, despesas e Pacientes & planos. Defina o valor da sessão no paciente e classifique o atendimento em Sessões a classificar — senão a receita não fecha.',
    ctaLabel: 'Ir à Ivy',
    viewport: 'both',
    requires: 'finance',
  },
  {
    id: 'pro-copilot',
    route: '/copilot',
    target: 'copilot-gate',
    fallbackTarget: 'nav-copilot',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'IVY - Assistente Virtual',
    body:
      'Aqui eu sou a assistente do consultório: você escolhe o paciente e o contexto trava nele. Isso é diferente do chat do paciente no portal — lá eu sou acompanhante, não substituto da sessão.',
    ctaLabel: 'Ver sessão',
    viewport: 'both',
  },
  {
    id: 'pro-session',
    route: '/session',
    target: 'session-gate',
    fallbackTarget: 'nav-session',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Iniciar sessão',
    body:
      'Assim como o Copiloto, a sessão vive fora da central: você escolhe o paciente e o contexto trava nele. Também dá para iniciar de dentro do prontuário, já com a pessoa certa.',
    ctaLabel: 'Continuar',
    viewport: 'both',
  },
  {
    id: 'pro-settings',
    route: '/settings',
    target: 'nav-settings',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Plano da clínica',
    body:
      'Em Perfil e configurações ficam a assinatura da Unithery, o upgrade e os dados do consultório. Não misture com a Ivy do paciente — aquela assinatura é no portal dele.',
    ctaLabel: 'Concluir',
    viewport: 'both',
    requires: 'owner',
  },
  {
    id: 'pro-close',
    route: '/dashboard',
    pose: 'happy',
    placement: 'inline',
    title: 'Pode explorar com calma',
    body:
      'Quando quiser, eu repito este caminho em Ajuda. Se pular um passo agora, nada se perde — a plataforma já está pronta.',
    ctaLabel: 'Começar a usar',
    viewport: 'both',
  },
];

const CLINIC_ADMIN_STEPS: TheryTourStep[] = [
  {
    id: 'admin-dashboard',
    route: '/dashboard',
    target: 'nav-dashboard',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'O pulso da clínica',
    body:
      'O Dashboard junta equipe, ocupação e o que precisa de atenção hoje. É o ponto de partida — o prontuário de cada pessoa fica em Pacientes.',
    ctaLabel: 'Ver Pacientes',
    viewport: 'both',
  },
  {
    id: 'admin-patients',
    route: '/patients',
    target: 'cta-new-patient',
    fallbackTarget: 'nav-patients',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Pacientes da clínica',
    body:
      'Cadastre ou abra um paciente para ver o prontuário. A cota do plano aparece quando o limite de ativos está perto.',
    ctaLabel: 'Continuar',
    viewport: 'both',
  },
  {
    id: 'admin-patient-hub',
    route: '/patients/:patientId/copilot',
    target: 'patient-tabs',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Prontuário isolado',
    body:
      'Cada ficha é de uma pessoa só: sessões, check-ins, clínica e documentos. A equipe trabalha no mesmo registro, sem misturar pacientes.',
    ctaLabel: 'Ver ficha clínica',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'admin-clinical',
    route: '/patients/:patientId/clinical',
    target: 'patient-tab-clinical',
    fallbackTarget: 'patient-tabs',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Ficha clínica',
    body:
      'Anamnese, hipóteses e o quadro atual. A equipe trabalha no mesmo registro — cada ficha é de uma pessoa só.',
    ctaLabel: 'Ver financeiro',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'admin-patient-finance',
    route: '/patients/:patientId/financeiro',
    target: 'patient-tab-financeiro',
    fallbackTarget: 'patient-tabs',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Financeiro deste paciente',
    body:
      'Contrato, valor da sessão e o que já foi pago desta pessoa. O caixa da clínica fica no Financeiro do menu; aqui é o combinado deste prontuário.',
    ctaLabel: 'Ver documentos',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'admin-documents',
    route: '/patients/:patientId/documents',
    target: 'patient-tab-documents',
    fallbackTarget: 'patient-tabs',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Documentos salvos',
    body:
      'Relatórios e artefatos guardados neste prontuário. Isolados por paciente, visíveis para quem tem acesso à ficha.',
    ctaLabel: 'Ver acesso da família',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'admin-family-invite',
    route: '/patients/:patientId/documents',
    target: 'cta-family-invite',
    fallbackTarget: 'cta-patient-actions',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Gerar acesso família',
    body:
      'Gera o código para o responsável ou o próprio paciente entrar no app. Sem o convite, check-ins e diário não chegam ao prontuário.',
    ctaLabel: 'Ver vínculo',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'admin-manage-link',
    route: '/patients/:patientId/documents',
    target: 'cta-manage-link',
    fallbackTarget: 'cta-patient-actions',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Gerenciar o vínculo',
    body:
      'Arquiva o paciente na lista inativa ou encerra o acompanhamento. O histórico clínico permanece no arquivo da clínica.',
    ctaLabel: 'Ver equipe',
    viewport: 'both',
    requires: 'patient',
  },
  {
    id: 'admin-team',
    route: '/professionals',
    target: 'nav-professionals',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Terapeutas da casa',
    body:
      'Aqui você convida e gerencia a equipe. Cada profissional vê só os pacientes que lhe cabem.',
    ctaLabel: 'Ver configurações',
    viewport: 'both',
  },
  {
    id: 'admin-settings',
    route: '/settings',
    target: 'nav-settings',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Plano e dados da clínica',
    body:
      'Assinatura, limites e perfil da clínica ficam em Perfil e configurações. É o lugar para upgrade ou cancelamento do plano Unithery.',
    ctaLabel: 'Concluir',
    viewport: 'both',
    requires: 'owner',
  },
  {
    id: 'admin-close',
    route: '/dashboard',
    pose: 'happy',
    placement: 'inline',
    title: 'Clínica pronta para o dia',
    body: 'Se quiser rever este mapa, abra Ajuda e peça para eu mostrar de novo.',
    ctaLabel: 'Começar a usar',
    viewport: 'both',
  },
];

const PATIENT_STEPS: TheryTourStep[] = [
  {
    id: 'self-diary',
    route: '/portal/diary',
    target: 'portal-diary',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Meu dia',
    body:
      'Aqui você registra como foi o dia — humor, sono, o que pesou. Seu psicólogo vê isso depois, no prontuário.',
    ctaLabel: 'Ver Histórico',
    viewport: 'both',
  },
  {
    id: 'self-history',
    route: '/portal/calendar',
    target: 'portal-calendar',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Histórico',
    body: 'O calendário guarda o que você já registrou. Serve para olhar atrás sem precisar procurar conversa antiga.',
    ctaLabel: 'Conhecer a Ivy',
    viewport: 'both',
  },
  {
    id: 'self-thery',
    route: '/portal/ivy',
    target: 'portal-thery',
    pose: 'happy',
    placement: 'spotlight',
    title: 'Conversar comigo',
    body:
      'No centro do menu estou eu. Entre as sessões, escreva ou fale. Não sou psicóloga: em emergência, 188 ou 192. Se ainda não assinou, os 7 dias grátis começam aqui.',
    ctaLabel: 'Ver o plano',
    viewport: 'both',
  },
  {
    id: 'self-plan',
    route: '/portal/agreements',
    target: 'portal-agreements',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Plano de cuidados',
    body: 'Combinados e materiais que o seu psicólogo compartilhou com você. É o combinado da terapia, não um contrato frio.',
    ctaLabel: 'Ver Ajuda',
    viewport: 'both',
  },
  {
    id: 'self-help',
    route: '/ajuda',
    target: 'portal-ajuda',
    fallbackTarget: 'nav-ajuda',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Ajuda humana',
    body:
      'Dúvida de conta, cobrança ou acesso: fale com a equipe da Unithery. Isso não passa por mim — é gente de verdade.',
    ctaLabel: 'Concluir',
    viewport: 'both',
  },
  {
    id: 'self-close',
    route: '/portal/diary',
    pose: 'happy',
    placement: 'inline',
    title: 'Pode entrar no seu ritmo',
    body:
      'Meu dia, Histórico e o botão do meio. Se quiser que eu explique de novo, é só abrir Ajuda.',
    ctaLabel: 'Começar a usar',
    viewport: 'both',
  },
];

const CAREGIVER_STEPS: TheryTourStep[] = [
  {
    id: 'care-diary',
    route: '/portal/diary',
    target: 'portal-diary',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Diário',
    body:
      'Registre o dia de quem você acompanha: o que comeu, dormiu, o que pesou. O terapeuta lê isso no prontuário.',
    ctaLabel: 'Ver calendário',
    viewport: 'both',
  },
  {
    id: 'care-calendar',
    route: '/portal/calendar',
    target: 'portal-calendar',
    pose: 'pointing',
    placement: 'spotlight',
    title: 'Calendário',
    body: 'Aqui ficam os registros já feitos. Útil para lembrar o que aconteceu na semana sem reescrever tudo.',
    ctaLabel: 'Ver combinados',
    viewport: 'both',
  },
  {
    id: 'care-agreements',
    route: '/portal/agreements',
    target: 'portal-agreements',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Relatórios e combinados',
    body: 'O que o terapeuta compartilhou com a família — combinados, relatórios e materiais de cuidado.',
    ctaLabel: 'Ver Ajuda',
    viewport: 'both',
  },
  {
    id: 'care-help',
    route: '/ajuda',
    target: 'portal-ajuda',
    fallbackTarget: 'nav-ajuda',
    pose: 'profile',
    placement: 'spotlight',
    title: 'Ajuda humana',
    body: 'Conta, acesso ou convite: fale com a equipe. Eu não resolvo cobrança nem senha.',
    ctaLabel: 'Concluir',
    viewport: 'both',
  },
  {
    id: 'care-close',
    route: '/portal/diary',
    pose: 'happy',
    placement: 'inline',
    title: 'Você já sabe o caminho',
    body: 'Diário, calendário e combinados. Se quiser repetir o mapa, abra Ajuda.',
    ctaLabel: 'Começar a usar',
    viewport: 'both',
  },
];

export function scriptForAudience(audience: TheryTourAudience): TheryTourStep[] {
  switch (audience) {
    case 'clinic_admin':
      return CLINIC_ADMIN_STEPS;
    case 'patient':
      return PATIENT_STEPS;
    case 'caregiver':
      return CAREGIVER_STEPS;
    default:
      return PROFESSIONAL_STEPS;
  }
}

export const TOUR_SCRIPTS = {
  professional: PROFESSIONAL_STEPS,
  clinic_admin: CLINIC_ADMIN_STEPS,
  patient: PATIENT_STEPS,
  caregiver: CAREGIVER_STEPS,
} as const;
