#!/bin/bash
# Unithery — Deploy de todas as Edge Functions (CORS global via _shared/cors.ts)
# Uso: ./scripts/deploy-functions.sh
# Pré-requisito: npx supabase login && npx supabase link --project-ref <ref>

set -e

FUNCTIONS=(
  "register-clinic"
  "register-family"
  "register-professional"
  "create-patient"
  "list-patients"
  "list-professionals"
  "update-professional"
  "generate-invite"
  "validate-invite"
  "link-family-account"
  "submit-diary"
  "upload-audio"
  "process-audio"
  "query-copilot"
  "transcribe-copilot-audio"
  "get-clinic-dashboard"
  "get-clinic-settings"
  "update-clinic-settings"
  "list-invoices"
  "get-professional-morning-briefing"
  "list-pending-evolutions"
  "get-daily-sessions"
  "get-monthly-summary"
  "create-schedule"
  "reschedule-session"
  "list-agreements"
  "toggle-agreement"
  "create-agreement"
  "get-patient-record"
  "get-session-recommendations"
  "generate-patient-summary"
  "generate-proactive-summary"
  "get-pdf-data"
  "get-family-calendar-status"
  "get-latest-agreements"
  "process-family-audio"
  "register-push-subscription"
  "check-and-send-reminders"
  "process-clinical-return"
  "generate-report-summary"
  "update-report"
  "list-all-reports"
  "verify-patient-cpf"
  "reactivate-patient"
  "manage-patient-link"
  "get-archived-patients"
  "get-plan-control-state"
  "purchase-addon-bypass"
  "delete-saved-recommendation"
  "get-paywall-state"
  "process-checkout-bypass"
  "save-recommendation"
  "list-saved-recommendations"
  "save-ai-artifact"
  "list-ai-artifact-status"
  "get-patient-artifacts"
  "clear-alerts"
  "get-patient-crisis-calendar"
  "update-patient"
  "get-patient-sessions"
  "upload-patient-avatar"
  "upload-professional-avatar"
)

echo "Deploying ${#FUNCTIONS[@]} Edge Functions..."
for func in "${FUNCTIONS[@]}"; do
  echo ">> $func"
  npx supabase functions deploy "$func" --no-verify-jwt
done
echo "Done."
